modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="ars_compressura"
version="${file.jarVersion}"
displayName="Ars Compressūra"
credits="A bunch of Starbuncles"
authors="Noah"
description='A small storage-block addon for Ars Nouveau Essence items.'


[[mixins]]
config="ars_compressura.mixins.json"

[[dependencies.ars_compressura]]
modId = "minecraft"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ars_compressura]]
modId = "ars_nouveau"
versionRange = "[1.21.1-5.4,)"
ordering = "AFTER"
side = "BOTH"